routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@index");
Route::resource('car', 'CarController');
Route::resource('driver', 'DriverController');
Route::resource('journey', 'JourneyController');
Route::get('get-distance','JourneyController@getDistance');

app/Driver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Driver extends Model
{
    protected $fillable = ['name','banglai','ngaycapbang','thoihangbanglai','organization_id','published'];
}

app/Http/Controllers/DriverController.php
<?php

namespace App\Http\Controllers;

use App\Driver;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class DriverController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Driver::paginate(20);
        return view('drivers.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('drivers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => ['required'],
            'banglai' => ['required'],
            'ngaycapbang' => ['required'],
            'thoihangbanglai' => ['required']
        ]);
        if($request->has('published')) {
            $request->merge(['published'=>1]);
        }else{
            $request->merge(['published'=>0]);
        }
        $request->merge(['organization_id'=>1]);
        $item = new Driver($request->except('_token'));
        $item->save();
        return redirect()->route('driver.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Driver  $driver
     * @return \Illuminate\Http\Response
     */
    public function show(Driver $driver)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Driver  $driver
     * @return \Illuminate\Http\Response
     */
    public function edit(Driver $driver)
    {
        return view('drivers.edit',compact('driver'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Driver  $driver
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Driver $driver)
    {
        $validatedData = $request->validate([
            'name' => ['required'],
            'banglai' => ['required'],
            'ngaycapbang' => ['required'],
            'thoihangbanglai' => ['required']
        ]);
        if($request->has('published')) {
            $request->merge(['published'=>1]);
        }else{
            $request->merge(['published'=>0]);
        }
        $request->merge(['organization_id'=>1]);
        $driver->update($request->except('_token'));
        return redirect()->route('driver.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Driver  $driver
     * @return \Illuminate\Http\Response
     */
    public function destroy(Driver $driver)
    {
        $driver->delete();
        return redirect()->route('driver.index')->with('info',"Xóa xong!");
    }
}

resources/views/drivers/create.blade.php
@extends('index')

@section('pagetitle', __("home.driver_create"))

@push('scripts')
    
@endpush

@section('content')
    <div class="container">
        <h3 class="my-3">{{ __("home.driver_create") }}</h3>
        <form action="{{ route('driver.store') }}" class="car-create" method="POST">
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="driverName">{{ __('home.driver_name') }}</label>
                  <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="driverName">
                </div>
                <div class="form-group col-md-6">
                  <label for="carLicense">{{ __('home.driver_license') }}</label>
                  <input type="text" name="banglai" class="form-control @error('banglai') is-invalid @enderror" id="carLicense">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carDangki">{{ __('home.driver_ngaycapbang') }}</label>
                  <input type="date" name="ngaycapbang" class="form-control @error('ngaycapbang') is-invalid @enderror" id="carDangki">
                </div>
                <div class="form-group col-md-6">
                  <label for="carDangkiem">{{ __('home.driver_thoihangbanglai') }}</label>
                  <input type="date" name="thoihangbanglai" class="form-control @error('thoihangbanglai') is-invalid @enderror" id="carDangkiem">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="custom-control custom-switch mb-2">
                        <input type="checkbox" name="published" checked class="custom-control-input" id="carPublished">
                        <label class="custom-control-label" for="carPublished">{{ __("home.published") }}</label>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button type="submit" class="btn btn-success btn-block">{{ __('home.save') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button type="reset" class="btn btn-warning btn-block">{{ __('home.reset') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <a class="btn btn-danger btn-block" href="{{ route('driver.index') }}">{{ __('home.cancel') }}</a>
                </div>
            </div>
        </form>        
    </div>    
@endsection

resources/views/drivers/edit.blade.php
@extends('index')

@section('pagetitle', __("home.driver_update"))

@push('scripts')
    <script src="{{ asset('js/form_edit.js') }}"></script>
@endpush

@section('content')
    <div class="container">
        <h3 class="my-3">{{ __("home.driver_update") }}</h3>
        <form action="{{ route('driver.update',$driver) }}" class="car-create" method="POST">
            @method('PUT')
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carName">{{ __('home.driver_name') }}</label>
                  <input type="text" name="name" value="{{ $driver->name }}" class="form-control @error('name') is-invalid @enderror" id="carName">
                </div>
                <div class="form-group col-md-6">
                  <label for="carLicense">{{ __('home.driver_license') }}</label>
                  <input type="text" name="banglai" value="{{ $driver->banglai }}" class="form-control @error('banglai') is-invalid @enderror" id="carLicense">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carDangki">{{ __('home.driver_ngaycapbang') }}</label>
                  <input type="date" name="ngaycapbang" value="{{ $driver->ngaycapbang }}" class="form-control @error('ngaycapbang') is-invalid @enderror" id="carDangki">
                </div>
                <div class="form-group col-md-6">
                  <label for="carDangkiem">{{ __('home.driver_thoihangbanglai') }}</label>
                  <input type="date" name="thoihangbanglai" value="{{ $driver->thoihangbanglai }}" class="form-control @error('thoihangbanglai') is-invalid @enderror" id="carDangkiem">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="custom-control custom-switch mb-2">
                        <input type="checkbox" name="published" @if($driver->published==1) {{ "checked" }} @endif class="custom-control-input" id="carPublished">
                        <label class="custom-control-label" for="carPublished">{{ __("home.published") }}</label>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button type="submit" class="btn btn-success btn-block">{{ __('home.save') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button id="deleteBtn" type="button" class="btn btn-warning btn-block">{{ __('home.delete') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <a class="btn btn-danger btn-block" href="{{ route('car.index') }}">{{ __('home.cancel') }}</a>
                </div>
            </div>
        </form>
        <form id="deleteFrm" method="POST" action="{{ route('car.destroy',$driver) }}">
            @method("DELETE")
            @csrf
        </form>
    </div>    
@endsection

resources/views/drivers/index.blade.php
@extends('index')

@section('pagetitle', __("home.car_list"))

@push('scripts')

@endpush

@section('content')
    <div class="container">
        <h3 class="my-3 text-center">{{ __("home.car_list") }}</h3>
        <div class="col">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col" class="text-center">{{ __('home.driver_name') }}</th>
                        <th scope="col" class="text-center">{{ __('home.driver_license') }}</th>
                        <th scope="col" class="text-center">{{ __('home.driver_ngaycapbang') }}</th>
                        <th scope="col" class="text-center">{{ __('home.driver_thoihangbanglai') }}</th>
                        <th scope="col" class="text-center">{{ __('home.published') }}</th>
                        <th scope="col" class="text-center">{{ __('home.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($items as $item)
                            <tr>
                                <td scope="row">{{ $item->id }}</td>
                                <td class="text-center"><a href="{{ route('car.edit',$item) }}">{{ $item->name }}</a></td>
                                <td><a href="{{ route('driver.edit',$item) }}">{{ $item->banglai }}</a></td>
                                <td class="text-center">{{ $item->ngaycapbang }}</td>
                                <td class="text-center">{{ $item->thoihangbanglai }}</td>
                                <td class="text-center">
                                    @if($item->published==1)
                                        <i class="fa text-success fa-check"></i>
                                    @else
                                        <i class="fa text-danger fa-times"></i>
                                    @endif
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-info" href="{{ route('driver.edit',$item) }}"><i class="fa fa-edit"></i></a>
                                    <form class="d-inline" method="POST" action="{{ route('driver.destroy',$item) }}">
                                        @method("DELETE")
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach    
                    </tbody>    
                </table>
            </div>    
        </div>
        <div class="col text-center">{{ $items->links() }}</div>       
    </div>    
@endsection