routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@index");
Route::resource('car', 'CarController');
Route::resource('driver', 'DriverController');
Route::resource('journey', 'JourneyController');
Route::get('get-distance','JourneyController@getDistance');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $fillable = ['name','alias','bienso','loainhienlieu','mucnhienlieu','dangki','dangkiem','kmhientai','namsx','published','organization_id'];
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Car::paginate(20);
        return view('cars.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'bienso' => ['required', 'unique:cars', 'max:255'],
            'mucnhienlieu' => ['required'],
        ]);
        if($request->has('published')) {
            $request->merge(['published'=>1]);
        }else{
            $request->merge(['published'=>0]);
        }
        $request->merge(['alias'=>Str::slug($request->bienso),'organization_id'=>1]);
        $car = new Car($request->except('_token'));
        $car->save();
        return redirect()->route('car.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        return view('cars.edit',compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Car $car)
    {
        $validatedData = $request->validate([
            'bienso' => ['required'],
            'mucnhienlieu' => ['required'],
        ]);
        if($request->has('published')) {
            $request->merge(['published'=>1]);
        }else{
            $request->merge(['published'=>0]);
        }
        $request->merge(['alias'=>Str::slug($request->bienso),'organization_id'=>1]);
        $car->update($request->except('_token'));
        return redirect()->route('car.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        $car->delete();
        return redirect()->route('car.index')->with('info',"Xóa xong!");
    }
}

resources/views/cars/create.blade.php
@extends('index')

@section('pagetitle', __("home.car_create"))

@push('scripts')
    
@endpush

@section('content')
    <div class="container">
        <h3 class="my-3">{{ __("home.car_create") }}</h3>
        <form action="{{ route('car.store') }}" class="car-create" method="POST">
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carName">{{ __('home.car_name') }}</label>
                  <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="carName">
                </div>
                <div class="form-group col-md-6">
                  <label for="carLicense">{{ __('home.car_license') }}</label>
                  <input type="text" name="bienso" class="form-control @error('bienso') is-invalid @enderror" id="carLicense">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carFuelType">{{ __('home.car_fuel_type') }}</label>
                  <select name="loainhienlieu" class="form-control @error('loainhienlieu') is-invalid @enderror" id="carFuelType">
                      <option value="1">{{ __("home.fuel_type_1") }}</option>
                      <option value="2">{{ __("home.fuel_type_2") }}</option>
                      <option value="3">{{ __("home.fuel_type_3") }}</option>
                  </select>
                </div>
                <div class="form-group col-md-6">
                  <label for="carFuel">{{ __('home.car_fuel') }}</label>
                  <input type="number" name="mucnhienlieu" class="form-control @error('mucnhienlieu') is-invalid @enderror" id="carFuel">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carDangki">{{ __('home.car_dangki') }}</label>
                  <input type="date" name="dangki" class="form-control @error('dangki') is-invalid @enderror" id="carDangki">
                </div>
                <div class="form-group col-md-6">
                  <label for="carDangkiem">{{ __('home.car_dangkiem') }}</label>
                  <input type="date" name="dangkiem" class="form-control @error('dangkiem') is-invalid @enderror" id="carDangkiem">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carkmhientai">{{ __('home.car_kmhientai') }}</label>
                  <input type="number" name="kmhientai" class="form-control @error('kmhientai') is-invalid @enderror" id="carkmhientai">
                </div>
                <div class="form-group col-md-6">
                  <label for="carNSX">{{ __('home.car_namsx') }}</label>
                  <input type="number" min="1980" max="2099" step="1" name="namsx" class="form-control @error('namsx') is-invalid @enderror" id="carNSX">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="custom-control custom-switch mb-2">
                        <input type="checkbox" name="published" checked class="custom-control-input" id="carPublished">
                        <label class="custom-control-label" for="carPublished">{{ __("home.published") }}</label>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button type="submit" class="btn btn-success btn-block">{{ __('home.save') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button type="reset" class="btn btn-warning btn-block">{{ __('home.reset') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <a class="btn btn-danger btn-block" href="{{ route('car.index') }}">{{ __('home.cancel') }}</a>
                </div>
            </div>
        </form>        
    </div>    
@endsection

resources/views/cars/edit.blade.php
@extends('index')

@section('pagetitle', __("home.car_update"))

@push('scripts')
    <script src="{{ asset('js/form_edit.js') }}"></script>
@endpush

@section('content')
    <div class="container">
        <h3 class="my-3">{{ __("home.car_update") }}</h3>
        <form action="{{ route('car.update',$car) }}" class="car-create" method="POST">
            @method('PUT')
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carName">{{ __('home.car_name') }}</label>
                  <input type="text" name="name" value="{{ $car->name }}" class="form-control @error('name') is-invalid @enderror" id="carName">
                </div>
                <div class="form-group col-md-6">
                  <label for="carLicense">{{ __('home.car_license') }}</label>
                  <input type="text" name="bienso" value="{{ $car->bienso }}" class="form-control @error('bienso') is-invalid @enderror" id="carLicense">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carFuelType">{{ __('home.car_fuel_type') }}</label>
                  <select name="loainhienlieu" class="form-control @error('loainhienlieu') is-invalid @enderror" id="carFuelType">
                      <option @if($car->loainhienlieu==1) {{ "selected" }} @endif value="1">{{ __("home.fuel_type_1") }}</option>
                      <option @if($car->loainhienlieu==2) {{ "selected" }} @endif value="2">{{ __("home.fuel_type_2") }}</option>
                      <option @if($car->loainhienlieu==3) {{ "selected" }} @endif value="3">{{ __("home.fuel_type_3") }}</option>
                  </select>
                </div>
                <div class="form-group col-md-6">
                  <label for="carFuel">{{ __('home.car_fuel') }}</label>
                  <input type="number" name="mucnhienlieu" value="{{ $car->mucnhienlieu }}" class="form-control @error('mucnhienlieu') is-invalid @enderror" id="carFuel">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carDangki">{{ __('home.car_dangki') }}</label>
                  <input type="date" name="dangki" value="{{ $car->dangki }}" class="form-control @error('dangki') is-invalid @enderror" id="carDangki">
                </div>
                <div class="form-group col-md-6">
                  <label for="carDangkiem">{{ __('home.car_dangkiem') }}</label>
                  <input type="date" name="dangkiem" value="{{ $car->dangkiem }}" class="form-control @error('dangkiem') is-invalid @enderror" id="carDangkiem">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="carkmhientai">{{ __('home.car_kmhientai') }}</label>
                  <input type="number" name="kmhientai" value="{{ $car->kmhientai }}" class="form-control @error('kmhientai') is-invalid @enderror" id="carkmhientai">
                </div>
                <div class="form-group col-md-6">
                  <label for="carNSX">{{ __('home.car_namsx') }}</label>
                  <input type="number" min="1980" max="2099" step="1" name="namsx" value="{{ $car->namsx }}" class="form-control @error('namsx') is-invalid @enderror" id="carNSX">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="custom-control custom-switch mb-2">
                        <input type="checkbox" name="published" @if($car->published==1) {{ "checked" }} @endif class="custom-control-input" id="carPublished">
                        <label class="custom-control-label" for="carPublished">{{ __("home.published") }}</label>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button type="submit" class="btn btn-success btn-block">{{ __('home.save') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <button id="deleteBtn" type="button" class="btn btn-warning btn-block">{{ __('home.delete') }}</button>
                </div>
                <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                    <a class="btn btn-danger btn-block" href="{{ route('car.index') }}">{{ __('home.cancel') }}</a>
                </div>
            </div>
        </form>
        <form id="deleteFrm" method="POST" action="{{ route('car.destroy',$car) }}">
            @method("DELETE")
            @csrf
        </form>
    </div>    
@endsection

resources/views/cars/index.blade.php
@extends('index')

@section('pagetitle', __("home.car_list"))

@push('scripts')

@endpush

@section('content')
    <div class="container">
        <h3 class="my-3 text-center">{{ __("home.car_list") }}</h3>
        <div class="col">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col" class="text-center">{{ __('home.car_name') }}</th>
                        <th scope="col" class="text-center">{{ __('home.car_license') }}</th>
                        <th scope="col" class="text-center">{{ __('home.car_fuel_type') }}</th>
                        <th scope="col" class="text-center">{{ __('home.car_fuel') }}</th>
                        <th scope="col" class="text-center">{{ __('home.car_dangki') }}</th>
                        <th scope="col" class="text-center">{{ __('home.car_dangkiem') }}</th>
                        <th scope="col" class="text-center">{{ __('home.published') }}</th>
                        <th scope="col" class="text-center">{{ __('home.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($items as $item)
                            <tr>
                                <td scope="row">{{ $item->id }}</td>
                                <td class="text-center"><a href="{{ route('car.edit',$item) }}">{{ $item->name }}</a></td>
                                <td><a href="{{ route('car.edit',$item) }}">{{ $item->bienso }}</a></td>
                                <td class="text-center">
                                    @switch($item->loainhienlieu)
                                        @case(1)
                                            {{ __('home.fuel_type_1') }}
                                            @break
                                        @case(2)
                                            {{ __('home.fuel_type_2') }}
                                            @break
                                        @case(3)
                                            {{ __('home.fuel_type_3') }}
                                            @break
                                        @default
                                        
                                    @endswitch
                                </td>
                                <td class="text-center">{{ $item->mucnhienlieu }}</td>
                                <td class="text-center">{{ $item->dangki }}</td>
                                <td class="text-center">{{ $item->dangkiem }}</td>
                                <td class="text-center">
                                    @if($item->published==1)
                                        <i class="fa text-success fa-check"></i>
                                    @else
                                        <i class="fa text-danger fa-times"></i>
                                    @endif
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-info" href="{{ route('car.edit',$item) }}"><i class="fa fa-edit"></i></a>
                                    <form class="d-inline" method="POST" action="{{ route('car.destroy',$item) }}">
                                        @method("DELETE")
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>                            
                        @endforeach    
                    </tbody>    
                </table>
            </div>    
        </div>
        <div class="col text-center">{{ $items->links() }}</div>       
    </div>    
@endsection