routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@index");
Route::resource('car', 'CarController');
Route::resource('driver', 'DriverController');
Route::resource('journey', 'JourneyController');
Route::get('get-distance','JourneyController@getDistance');

app/Journey.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Journey extends Model
{
    protected $fillable = ['name','ngaydi','ngayve','sokm','giaxang','organization_id','published'];
    public function cars() {
        return $this->belongsToMany('App\Car');
    }
}

app/Http/Controllers/JourneyController.php
<?php

namespace App\Http\Controllers;

use App\Journey;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class JourneyController extends Controller
{
    public function getDistance(Request $request) {
        $data = $request->all();
        
        $waypoints = urlencode("Thái Bình|Nam Định");

        $ggurl = "https://maps.googleapis.com/maps/api/directions/json?key=AIzaSyAQAGv-AmIr0j3rSKvKNtjnJ36FcK-w8C8&origin=".urlencode($data['origins']).'&destination='.urlencode($data['dest']).'&waypoints='.$waypoints;
        
        //$ggurl = "https://maps.googleapis.com/maps/api/distancematrix/json?key=AIzaSyAQAGv-AmIr0j3rSKvKNtjnJ36FcK-w8C8&origins=Thai+Nguyen&destinations=Nghe+An";
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $ggurl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        $response = curl_exec($ch);
        curl_close($ch);
        
        $response_a = json_decode($response);

        if($response_a->status=="OK") {
            $totalKm = 0;
            foreach ($response_a->routes[0]->legs as $key => $value) {
                $totalKm += $value->distance->value;
            }
            echo $totalKm/1000;
        }else{
            echo "0";
        }
        exit;
    }
    public function getGiaXang() {
        $petrolimex_url = "https://www.petrolimex.com.vn/";
        $content = file_get_contents($petrolimex_url);
        $content = explode('<div id="vie_p6_PortletContent">',$content);
        $content = explode('</div>',$content[1]);
        //$xang_95_v1 = strip_tags($content[4]);
        $xang_95_v2 = (double) strip_tags($content[5]);
        return $xang_95_v2;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Journey::paginate(20);
        return view('journeys.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $giaxang = $this->getGiaXang();
        return view('journeys.create',compact('giaxang'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Journey  $journey
     * @return \Illuminate\Http\Response
     */
    public function show(Journey $journey)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Journey  $journey
     * @return \Illuminate\Http\Response
     */
    public function edit(Journey $journey)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Journey  $journey
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Journey $journey)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Journey  $journey
     * @return \Illuminate\Http\Response
     */
    public function destroy(Journey $journey)
    {
        //
    }
}

resources/views/journeys/create.blade.php
@extends('index')

@section('pagetitle', __("home.journey_create"))

@push('scripts')
<script src="{{ asset('js/form_edit.js') }}"></script>
@endpush

@section('content')
    <div class="container">
        <h3 class="my-3 text-center">{{ __("home.journey_create") }}</h3>
        <div class="journey-create">
            <form action="{{ route('journey.store') }}" class="car-create" method="POST">
                @csrf
                <div class="form-row">
                    <div class="form-group col-12">
                      <label for="driverName">{{ __('home.journey_name') }}</label>
                      <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="driverName">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="journeydiemdi">{{ __('home.journey_diemdi') }}</label>
                      <input type="text" name="diemdi" class="form-control @error('diemdi') is-invalid @enderror" id="journeydiemdi">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="journeyCar">{{ __('home.car_name') }}</label>
                        <input type="text" name="car_id" class="form-control @error('car_id') is-invalid @enderror" id="journeyCar">
                    </div>                    
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="journeydiemden">{{ __('home.journey_diemden') }}</label>
                        <input type="text" name="diemden" class="form-control @error('diemden') is-invalid @enderror" id="journeydiemden">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="journeyDriver">{{ __('home.driver_name') }}</label>
                        <input type="text" name="driver_id" class="form-control @error('driver_id') is-invalid @enderror" id="journeyDriver">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="jouneyKm">{{ __('home.journey_sokm') }}</label>
                        <input type="text" disabled value="0" name="sokm" class="form-control @error('sokm') is-invalid @enderror" id="jouneyKm">
                    </div>
                    <div class="col-md-2 form-group"><label for="kocojca">&nbsp;</label><button id="calcDistance" type="button" class="btn btn-block btn-info">{{ __('home.tinhkm') }}</button></div>
                    <div class="form-group col-md-6">
                        <label for="journeyNgaydi">{{ __('home.journey_ngaydi') }}</label>
                        <input type="date" name="ngaydi" class="form-control @error('ngaydi') is-invalid @enderror" id="journeyNgaydi">
                    </div>                    
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="carLicense">{{ __('home.car_fuel') }}</label>
                        <input type="number" name="fuel" disabled class="form-control @error('fuel') is-invalid @enderror" id="carLicense">
                    </div>
                    
                    <div class="form-group col-md-6">
                      <label for="journeyNgayve">{{ __('home.journey_ngayve') }}</label>
                      <input type="date" name="ngayve" class="form-control @error('ngayve') is-invalid @enderror" id="journeyNgayve">
                    </div>
                </div>               

                <div class="row">
                    <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                        <button type="submit" class="btn btn-success btn-block">{{ __('home.save') }}</button>
                    </div>
                    <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                        <button type="reset" class="btn btn-warning btn-block">{{ __('home.reset') }}</button>
                    </div>
                    <div class="col-sm-6 col-md-3 col-lg-2 my-1">
                        <a class="btn btn-danger btn-block" href="{{ route('journey.index') }}">{{ __('home.cancel') }}</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/journeys/index.blade.php
@extends('index')

@section('pagetitle', __("home.journey_list"))

@push('scripts')

@endpush

@section('content')
    <div class="container">
        <h3 class="my-3 text-center">{{ __("home.journey_list") }}</h3>
        <div class="col">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col" class="text-center">{{ __('home.journey_name') }}</th>
                        <th scope="col" class="text-center">{{ __('home.journey_ngaydi') }}</th>
                        <th scope="col" class="text-center">{{ __('home.journey_ngayve') }}</th>
                        <th scope="col" class="text-center">{{ __('home.journey_sokm') }}</th>                       
                        <th scope="col" class="text-center">{{ __('home.published') }}</th>
                        <th scope="col" class="text-center">{{ __('home.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($items as $item)
                            <tr>
                                <td scope="row">{{ $item->id }}</td>
                                <td class="text-center"><a href="{{ route('journey.edit',$item) }}">{{ $item->name }}</a></td>
                                <td><a href="{{ route('journey.edit',$item) }}">{{ $item->ngaydi }}</a></td>
                                <td class="text-center">{{ $item->ngayve }}</td>
                                <td class="text-center">{{ $item->sokm }}</td>                           
                                <td class="text-center">
                                    @if($item->published==1)
                                        <i class="fa text-success fa-check"></i>
                                    @else
                                        <i class="fa text-danger fa-times"></i>
                                    @endif
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-info" href="{{ route('journey.edit',$item) }}"><i class="fa fa-edit"></i></a>
                                    <form class="d-inline" method="POST" action="{{ route('journey.destroy',$item) }}">
                                        @method("DELETE")
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach    
                    </tbody>    
                </table>
            </div>    
        </div>
        <div class="col text-center">{{ $items->links() }}</div>       
    </div>    
@endsection